services:
  client:
    build:
      context: ./client
    volumes:
      - staticbuild:/app/out
    networks:
      - dev

  nginx:
    build:
      context: ./nginx
    volumes:
      - staticbuild:/app/public
    ports:
      - “3000:80”
    networks:
      - dev

  networks:
    dev:
      driver: bridge

  volumes:
    staticbuild: