name: Deploy

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Rebuild and start docker container
        run: |
          docker compose up -d --build
        env:
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          FILE_STORAGE_URL: ${{ secrets.FILE_STORAGE_URL }}
