name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Create .env
        run: echo "${{ secrets.PROD_ENV_FILE }}" > .env

      - name: Clean docker images
        run: |
          docker system prune --all --force

      - name: Start docker container
        run: |
          docker compose up -d --build
